// <auto-generated />
namespace Transparent.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTagDescriptionAndTicketDiscriminator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTagDescriptionAndTicketDiscriminator));
        
        string IMigrationMetadata.Id
        {
            get { return "201412141932540_AddTagDescriptionAndTicketDiscriminator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
